### ISSUE TITLE
1.3.0 on npm is missing `build`

### ISSUE THREAD

**Issue by twhitbeck** [springload/react-accessible-headings#2]
1.3.0 is broken. The npm package is missing the `build` directory. I see that you added it to `.gitignore` which I think is a good idea, but you need the build dir to be present when you publish to npm. Also, you could probably have a `.npmignore` file to not include `src` in the npm package

**Comment by holloway** [comment]
@twhitbeck Fixed. Sorry about this. I'll leave this ticket open until you confirm that it's working for you.

**Comment by twhitbeck** [comment]
@holloway looks good. thanks mate!
